-- Auto-generated from schema-map-postgres.yaml (map@sha1:621FDD3D99B768B6A8AD92061FB029414184F4B3)
-- engine: postgres
-- table:  key_wrappers

CREATE TABLE IF NOT EXISTS key_wrappers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  wrapper_uuid CHAR(36) NOT NULL,
  kms1_key_id BIGINT NOT NULL,
  kms2_key_id BIGINT NOT NULL,
  dek_wrap1 BYTEA NOT NULL,
  dek_wrap2 BYTEA NOT NULL,
  crypto_suite JSONB NULL,
  wrap_version INTEGER NOT NULL DEFAULT 1,
  status TEXT NOT NULL DEFAULT 'active',
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  rotated_at TIMESTAMPTZ(6) NULL,
  CONSTRAINT uq_key_wrappers_uuid UNIQUE (wrapper_uuid),
  CONSTRAINT chk_kw_status CHECK (status IN ('active','rotated','retired','invalid'))
);
